version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neural_network_app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QWEN_URL=${QWEN_URL}
      - LLAMA_URL=${LLAMA_URL}
    volumes:
      # Монтирование текущей директории в контейнер для отслеживания изменений в реальном времени
      - .:/app
    tty: true
